# Generated by Django 5.1.8 on 2025-04-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='audio_file',
            field=models.FileField(upload_to='song_audio/'),
        ),
        migrations.AlterField(
            model_name='songs',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='song_images/'),
        ),
        migrations.AlterField(
            model_name='songs',
            name='lyrics',
            field=models.TextField(blank=True, null=True),
        ),
    ]
